pool:
  name: 'AutomationAgentPool'
  vmImage: 'ubuntu-latest'  # Use 'ubuntu-latest' for Linux machines

jobs:
- job: Job1
  displayName: 'First Job'
  steps:
  - bash: |
      echo "Hello from Job1"
      sleep 300  # Sleep for 5 minutes to ensure job takes 5 minutes
    displayName: 'Run Bash script for Job1'

  - bash: |
      echo "Checking Java installation..."
      java -version || echo "Java is not installed"
    displayName: 'Check Java Installation'

  - bash: |
      echo "Checking Maven installation..."
      mvn -v || echo "Maven is not installed"
    displayName: 'Check Maven Installation'

  - bash: |
      echo "Checking Chrome installation..."
      google-chrome --version || echo "Chrome is not installed"
    displayName: 'Check Chrome Installation'