pool:
  name: 'AutomationAgentPool'
  vmImage: 'ubuntu-latest'  # This is for a Linux-based agent

jobs:
- job: Job1
  displayName: 'First Job'
  steps:
  - script: |
      echo "Hello from Job1"
    displayName: 'Run Bash script for Job1'

- job: Job2
  displayName: 'Second Job'
  steps:
  - script: |
      echo "Hello from Job2"
    displayName: 'Run Bash script for Job2'

- job: Job3
  displayName: 'Third Job'
  steps:
  - script: |
      echo "Hello from Job3"
    displayName: 'Run Bash script for Job3'

- job: Job4
  displayName: 'Fourth Job'
  steps:
  - script: |
      echo "Hello from Job4"
    displayName: 'Run Bash script for Job4'

- job: Job5
  displayName: 'Fifth Job'
  steps:
  - script: |
      echo "Hello from Job5"
    displayName: 'Run Bash script for Job5'

- job: Job6
  displayName: 'Sixth Job'
  steps:
  - script: |
      echo "Hello from Job6"
    displayName: 'Run Bash script for Job6'

- job: Job7
  displayName: 'Seventh Job'
  steps:
  - script: |
      echo "Hello from Job7"
    displayName: 'Run Bash script for Job7'

- job: Job8
  displayName: 'Eighth Job'
  steps:
  - script: |
      echo "Hello from Job8"
    displayName: 'Run Bash script for Job8'

- job: Job9
  displayName: 'Ninth Job'
  steps:
  - script: |
      echo "Hello from Job9"
    displayName: 'Run Bash script for Job9'

- job: Job10
  displayName: 'Tenth Job'
  steps:
  - script: |
      echo "Hello from Job10"
    displayName: 'Run Bash script for Job10'

- job: Job11
  displayName: 'Eleventh Job'
  steps:
  - script: |
      echo "Hello from Job11"
    displayName: 'Run Bash script for Job11'

- job: Job12
  displayName: 'Twelfth Job'
  steps:
  - script: |
      echo "Hello from Job12"
    displayName: 'Run Bash script for Job12'

- job: Job13
  displayName: 'Thirteenth Job'
  steps:
  - script: |
      echo "Hello from Job13"
    displayName: 'Run Bash script for Job13'

- job: Job14
  displayName: 'Fourteenth Job'
  steps:
  - script: |
      echo "Hello from Job14"
    displayName: 'Run Bash script for Job14'

- job: Job15
  displayName: 'Fifteenth Job'
  steps:
  - script: |
      echo "Hello from Job15"
    displayName: 'Run Bash script for Job15'
