pool:
  name: 'AutomationAgentPool'
  vmImage: 'ubuntu-latest'  # This is for a Linux-based agent

jobs:
- job: Job1
  displayName: 'First Job'
  steps:
  - script: |
      echo "Hello from Job1"
    displayName: 'Run Bash script for Job1'

- job: Job2
  displayName: 'Second Job'
  steps:
  - script: |
      echo "Hello from Job2"
    displayName: 'Run Bash script for Job2'

- job: Job3
  displayName: 'Third Job'
  steps:
  - script: |
      echo "Hello from Job3"
    displayName: 'Run Bash script for Job3'
