pool:
  name: 'Pool-01'
  vmImage: 'windows-latest'  # You can specify the image for Windows if needed (e.g., windows-latest)

jobs:
- job: Job1
  displayName: 'First Job'
  steps:
  - powershell: |
      Write-Output "Hello from Job1"
    displayName: 'Run PowerShell script for Job1'

- job: Job2
  displayName: 'Second Job'
  steps:
  - powershell: |
      Write-Output "Hello from Job2"
    displayName: 'Run PowerShell script for Job2'

- job: Job3
  displayName: 'Third Job'
  steps:
  - powershell: |
      Write-Output "Hello from Job3"
    displayName: 'Run PowerShell script for Job3'
